config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "static_pages#home"
  resources :static_pages
  resources :users, only: [:show]
  resources :product_suggests
  resources :carts
  resources :products, only: [:show]
  resources :comments
  resources :orders
  namespace :admin do
    root "users#index"
    resources :categories
    resources :products
    resources :users
    resources :orders
    resources :product_suggests
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  end

  def update
    @cart.add_item params[:id]
    session["cart"] = @cart.serialize
  end

  def edit
    item = @cart.find_item params[:id]
    if item.quantity > 1
      item.abatement
      session["cart"] = @cart.serialize
    end
    respond_to do |format|
      format.js {render "update"}
    end
  end

  def destroy
    cart = session["cart"]
    item = cart["items"].find{|item| item["product_id"] == params[:id]}
    if item
      cart["items"].delete item
      initialize_cart
    end
    respond_to do |format|
      format.js {render "update"}
    end
  end
end

app/views/carts/_listing.html.erb
<div class="cart-item-show">
  <h3 class="col-md-offset-1 total-cart text-success">
    <b><%= t ".total" %>:</b>
      <%= number_to_currency @cart.total_price %></h3><hr>
  <% @cart.items.each do |item| %>
    <div class="col-md-4 col-md-offset-1">
      <%= image_tag item.product.image.url, class: "image-shop" %>
      <h4 class="media-heading">
        <%= link_to item.product.name, item.product %>
      </h4>
      <div class="media">
        <div class="media-body">
          <span class="text-success">
            <strong><%= t "products.status" %></strong></span>
          <span class="text-success"><strong></strong></span>
        </div>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th><%= t ".quantity" %></th>
            <th class="text-center"><%= t ".price" %></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="col-sm-2 col-md-2">
              <%= item.quantity %>
            </td>
            <td class="col-sm-3 col-md-3 text-center">
              <strong><%= number_to_currency item.total_price %></strong></td>
          </tr>
          <tr>
            <td></td>
            <td>
              <span class="item-right">
                <%= link_to t("delete"), cart_path(item.product_id),
                  method: :delete, remote: true,
                    class: "btn btn-xs btn-danger pull-right" %>
              </span>
              <%= link_to t(".sub"), edit_cart_path(item.product), remote: true,
                class: "pull-right btn btn-xs btn-primary" %>
              <%= link_to t(".add"), cart_path(item.product), remote: true,
                method: "PUT", class: "pull-right btn btn-xs btn-primary" %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/carts/index.html.erb
<div class="page-content">
  <div class="container">
    <div class="row">
      <%= render "listing" %>
    </div>
    <% if @cart.present? %>
      <%= link_to t(".order"), new_order_path,
        class: "pull-left btn btn-primary col-md-offset-1" %>
    <% end %>
  </div>
</div>

app/views/carts/update.js.erb
$('.cart-item-show').replaceWith('<%= escape_javascript render( partial: "carts/listing") %>');
$('.cart-item').replaceWith('<%= escape_javascript render(partial: "layouts/cart") %>');
$('.items-count').text('<%= @cart.count %>');