config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "static_pages#home"
  resources :static_pages
  resources :users, only: [:show]
  resources :product_suggests
  resources :carts
  resources :products, only: [:show]
  resources :comments
  resources :orders
  namespace :admin do
    root "users#index"
    resources :categories
    resources :products
    resources :users
    resources :orders
    resources :product_suggests
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product_suggests, dependent: :nullify
  has_many :products

  validates :name,  presence: true

  scope :order_name, -> {order :name}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate!, :authenticate_admin!
  before_action :load_category, only: [:edit, :destroy, :update]

  def index
    @q = Category.ransack params[:q]
    @categories = @q.result.page(params[:page]).per Settings.page_per
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "flash.success.create"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def destroy
    if @category.products.blank?
      if @category.destroy
        flash.now[:success] = t "admin.categories.destroy.success"
      end
    else
      flash.now[:danger] = t "admin.categories.destroy.danger"
    end
    respond_to do |format|
      format.json do
        render json: {flash: flash}
      end
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "flash.success.update"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit :name, :description
  end

  def load_category
    @category = Category.find_by id: params[:id]
    if @category.nil?
      flash[:danger] = t "flash.danger.category_not_exist"
      redirect_to admin_categories_path
    end
  end
end

app/views/admin/categories/_form.html.erb
<%= simple_form_for [:admin, @category] do |f| %>
  <%= f.input :name, class: "form-control" %>
  <%= f.input :description, class: "form-control" %>
  <%= f.button :submit, t(".save"),
    class: "btn btn-primary col-md-1 col-md-offset-5" %>
<% end %>

app/views/admin/categories/_search_form.html.erb
<div class="row mg-bt-10">
  <div class="col-md-6">
    <%= search_form_for @q, url: admin_categories_path do |f| %>
      <div class="input-group col-md-8">
        <%= f.search_field :name_cont_any,
          class: "form-control", placeholder: t(".search") %>
        <span class="input-group-btn">
          <%= f.submit  class: "btn btn-danger" %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center"><%= t ".title" %></h1>
    <%= render "form", url: admin_category_path %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="content-page-admin">
  <h2 class="text-center"><%= t ".title" %></h2>
  <div class="flash-massage"></div>
  <%= render "search_form" %>
    <div class="mg-bt-10 pull-right">
      <%= link_to  t(".new"), new_admin_category_path,
        class: "btn btn btn-primary" %>
    </div>
    <table class="table table-bordered" id="table-category">
      <thead>
        <tr>
          <th><%= t ".number_order" %></th>
          <th><%= t ".name" %></th>
          <th><%= t ".description" %></th>
          <th><%= t ".created_at" %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each_with_index do |category, index| %>
          <tr>
            <td>
              <%= number_order params[:page] , index %>
            </td>
            <td><%= category.name %></td>
            <td><%= category.description %></td>
            <td><%= l category.created_at, format: :short_date %></td>
            <td class="text-center">
              <%= link_to edit_admin_category_path(category) do %>
                <i class="text-primary glyphicon glyphicon-edit"> </i>
              <% end %>
              <a class="btn-delete-category" data-value="<%= category.id %>">
                <i class="text-danger glyphicon glyphicon-trash"></i></a>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <%= paginate @categories, theme: "twitter-bootstrap-3" %>
</div>