config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "static_pages#home"
  resources :static_pages
  resources :users, only: [:show]
  resources :product_suggests
  resources :carts
  resources :products, only: [:show]
  resources :comments
  resources :orders
  namespace :admin do
    root "users#index"
    resources :categories
    resources :products
    resources :users
    resources :orders
    resources :product_suggests
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :comments
  has_many :order_items
  belongs_to :category

  validates_processing_of :image
  validate :image_size_validation
  validates :name, :price, :category_id, presence: true

  ratyrate_rateable "rate"

  private

  def image_size_validation
    if image.size > Settings.megabytes_image.megabytes
      errors[:image] << I18n.t("image_size")
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate!, :authenticate_admin!
  before_action :load_categories, except: [:index, :destroy]
  before_action :load_product, only: [:edit, :destroy, :update]

  def index
    @q = Product.ransack params[:q]
    @products = @q.result.page(params[:page]).per Settings.page_per
  end

  def new
    @product_suggest =  ProductSuggest.find_by id: params[:product]
    if @product_suggest
      @product = Product.new  name: @product_suggest.product_name,
        description: @product_suggest.description,
        image: @product_suggest.image,
        category_id: @product_suggest.category_id
    else
      @product = Product.new
    end
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t "flash.success.create"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t "flash.success.update"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    if @product.order_items.blank?
      if @product.destroy
        flash.now[:success] = t "admin.products.destroy.success"
      end
    else
      flash.now[:danger] = t "admin.products.destroy.danger"
    end
    respond_to do |format|
      format.json do
        render json: {flash: flash}
      end
    end
  end

  private

  def product_params
    params.require(:product)
      .permit :name, :description, :price, :image, :category_id, :remove_image
  end

  def load_categories
    @categories = Category.order_name
  end

  def load_product
    @product = Product.find_by id: params[:id]
    if @product.nil?
      flash[:danger] = t "flash.danger.product_not_exist"
      redirect_to admin_products_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  def show
    @comment = Comment.new if user_signed_in?
  end
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product], html: {multipart: true} do |f| %>
  <%= f.input :name, class: "form-control" %>
  <%= f.input :category_id, collection: @categories, class: "form-control" %>
  <%= f.input :description, class: "form-control" %>
  <%= f.input :price, class: "form-control" %>
  <% if f.object.image? %>
    <%= image_tag f.object.image.thumb.url %>
    <%= f.input :remove_image, as: :boolean,
      checked_value: true, unchecked_value: false %>
    <%= f.label :remove_image %>
  <% end %>
  <%= f.input :image, class: "form-control" %>
  <%= f.button :submit, t(".save"),
    class: "btn btn-primary col-md-1 col-md-offset-5" %>
<% end %>

app/views/admin/products/_search.html.erb
<div class="row mg-bt-10">
  <div class="col-md-6">
    <%= search_form_for [:admin, @q] do |f| %>
      <div class="input-group col-md-8">
        <%= f.search_field :name_cont_any,
          class: "form-control", placeholder: t(".placeholder") %>
        <span class="input-group-btn">
          <%= f.submit  class: "btn btn-danger" %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/products/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center"><%= t ".title" %></h1>
    <%= render "form" %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="content-page-admin">
  <h2 class="text-center"><%= t ".title" %></h2>
  <div class="flash-massage"></div>
  <%= render "search" %>
    <div class="mg-bt-10 pull-right">
      <%= link_to  t(".new"), new_admin_product_path,
        class: "btn btn btn-primary" %>
    </div>
    <table class="table table-bordered" id="table-product">
      <thead>
        <tr>
          <th><%= t ".number_order" %></th>
          <th><%= t ".category" %></th>
          <th><%= t ".name" %></th>
          <th><%= t ".description" %></th>
          <th><%= t ".created_at" %></th>
          <th><%= t ".image" %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each_with_index do |product, index| %>
          <tr>
            <td>
              <%= number_order params[:page] , index %>
            </td>
            <td><%= product.category.try :name %></td>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td><%= l product.created_at, format: :short_date %></td>
            <td><%= image_tag product.image.thumb.url %></td>
            <td class="text-center">
              <%= link_to edit_admin_product_path product do %>
                <i class="text-primary glyphicon glyphicon-edit"> </i>
              <% end %>
              <a class="btn-delete-product" data-value="<%= product.id %>">
                <i class="text-danger glyphicon glyphicon-trash"></i></a>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <%= paginate @products, theme: "twitter-bootstrap-3" %>
</div>