config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "static_pages#home"
  resources :static_pages
  resources :users, only: [:show]
  resources :product_suggests
  resources :carts
  resources :products, only: [:show]
  resources :comments
  resources :orders
  namespace :admin do
    root "users#index"
    resources :categories
    resources :products
    resources :users
    resources :orders
    resources :product_suggests
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_create :set_default_role
  mount_uploader :avatar, ImageUploader
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:google_oauth2, :facebook]

  has_many :product_suggests
  has_many :comments
  has_many :orders
  validates :name, presence: true, length: {maximum: 50}
  enum role: [:user, :admin]
  ratyrate_rater

  def is_user? user
    self == user
  end

  class << self
    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.name = auth.info.name
        user.password = Devise.friendly_token[0, 20]
        user.provider = auth.provider
        user.uid = auth.uid
      end
    end
  end

  private

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate!, :authenticate_admin!
  load_and_authorize_resource

  def index
    @q = User.user.ransack params[:q]
    @users = @q.result.page(params[:page]).per Settings.page_per
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "flash.success.create"
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "flash.success.update"
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash.now[:success] = t "flash.success.delete"
    end
    respond_to do |format|
      format.json do
        render json: {flash: flash}
      end
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :current_password, :phone, :gender, :avatar
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth request.env["omniauth.auth"]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      if is_navigational_format?
        set_flash_message(:notice, :success, kind: "Facebook")
      end
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      redirect_to root_path, flash: {error: t("login_error")}
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  def show
  end
end

app/views/admin/users/_form.html.erb
<div class="panel-body">
  <%= simple_form_for [:admin, @user], html: {multipart: true} do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :name, label: :name,
        required: true, autofocus: true  %>
      <%= f.input :email, required: true %>
      <%= f.input :password, required: true,
        hint: ("#{@minimum_password_length}
        characters minimum" if @minimum_password_length) %>
      <%= f.input :password_confirmation, required: true %>
      <%= f.label :phone %>
      <%= f.text_field :phone, class: "form-control" %>
      <%= f.label :gender %>
      <%= f.select :gender,[[t("user.gender.female"), true],
        [t("user.gender.male"), false]],
        prompt: t("user.gender.select"), required: true,
        placeholder: t("user.gender_holder"),
        class: "form-control" %>
      <%= f.input :avatar, class: "form-control" %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, t("admin.users.btn_submit"),
        class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/users/_search_form.html.erb
<div class="row mg-bt-10">
  <div class="col-md-6">
    <%= search_form_for [:admin, @q] do |f| %>
      <div class="input-group col-md-8">
        <%= f.search_field :name_cont_any,
          class: "form-control", placeholder: t("admin.users.placeholder") %>
        <span class="input-group-btn">
          <%= f.submit  class: "btn btn-danger" %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<% provide :title, t("admin.users.edit") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="text-center panel-title"><%= t "admin.users.edit" %></h1>
      </div>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide :title, t("admin.users.users") %>
<div class="content-page-admin">
  <h2 class="text-center"><%= t ".title" %></h2>
  <%= render "search_form" %>
  <div class="mg-bt-10 pull-right">
    <%= link_to  t("admin.users.new"), new_admin_user_path,
      class: "btn btn btn-primary" %>
  </div>
  <div class="flash-massage"></div>
  <table class="table table-bordered" id="table-users">
    <thead>
      <tr>
        <th><%= t "admin.users.number_order" %></th>
        <th><%= t ".name" %></th>
        <th><%= t ".email" %></th>
        <th><%= t ".phone" %></th>
        <th><%= t ".gender" %></th>
        <th><%= t ".avatar" %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each_with_index do |user, index| %>
        <tr id="user-<%= user.id %>">
          <td><%= number_order params[:page], index %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.phone %></td>
          <td><%= user.gender ? t(".female") : t(".male") %></td>
          <td><%= image_tag user.avatar.thumb.url %></td>
          <td class="text-center">
            <%= link_to edit_admin_user_path user do %>
              <i class="text-primary glyphicon glyphicon-edit"> </i>
            <% end %>
            <a class="btn-delete-user" data-value="<%= user.id %>">
              <i class="text-danger glyphicon glyphicon-trash"></i></a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @users, theme: "twitter-bootstrap-3" %>
</div>

app/views/admin/users/new.html.erb
<% provide :title, t("admin.users.new") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="text-center panel-title"><%= t "admin.users.new" %></h1>
      </div>
      <%= render "form" %>
    </div>
  </div>
</div>